# Generated by Django 5.2.5 on 2025-09-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimEvento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'dim_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimFecha',
            fields=[
                ('id_fecha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
                ('anho', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('dia_semana', models.CharField(max_length=10)),
                ('semana_anho', models.IntegerField()),
                ('nombre_mes', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dim_fecha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimUbicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dim_ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechosAsistenciaHumanitaria',
            fields=[
                ('id_hecho', models.AutoField(primary_key=True, serialize=False)),
                ('kit_sentencia', models.IntegerField()),
                ('kit_evento', models.IntegerField()),
                ('chapa_fibrocemento_cantidad', models.IntegerField()),
                ('chapa_zinc_cantidad', models.IntegerField()),
                ('colchones', models.IntegerField()),
                ('frazadas', models.IntegerField()),
                ('terciadas', models.IntegerField()),
                ('puntales', models.IntegerField()),
                ('carpas_plasticas', models.IntegerField()),
            ],
            options={
                'db_table': 'hechos_asistencia_humanitaria',
                'managed': False,
            },
        ),
    ]
